Ageforum/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from django.conf.urls import include
from forum import views as Ageforum_views
from django.conf.urls import handler404, handler500

urlpatterns = [
    path('admin', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('forum.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('robots.txt', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml', TemplateView.as_view(
        template_name="sitemap.xml", content_type="application/xml")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = Ageforum_views.error_404

forum/urls.py
from django.urls import path


from accounts import urls

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('discussion_create', views.discussion_create, name='discussion_create'),
    path('response_create/<int:discussion_id>',
         views.response_create, name='response_create'),
    path('response_reply_create/<int:discussion_id>/<int:message_id>',
         views.response_reply_create, name='response_reply_create'),
    path('<int:discussion_id>', views.discussion_detail, name='discussion_detail'),
    path('message_vote/<int:message_id>',
         views.message_vote, name='message_vote'),
    path('delete_discussion/<int:discussion_id>',
         views.delete_discussion, name='delete-discussion'),
    path('delete_response/<int:response_id>',
         views.delete_response, name='delete-response'),
    path('contact', views.contact, name='contact'),
    path('edit_text/<int:discussion_id>', views.edit_text, name='edit_text'),
    path('edit_response_text/<int:discussion_id>/<int:message_id>', views.edit_response_text, name='edit_response_text')

]

forum/models.py
from datetime import datetime
from django.db import connection, models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    AbstractUser._meta.get_field('email')._unique = True
    avatar = models.ImageField(upload_to='avatars', blank=True)
    biography = models.TextField(max_length=100, blank =True)
  


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=100000,blank=True)
    date_publication = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

    def __eq__(self, other):
        return self.id == other.id

    def __hash__(self):
        return super().__hash__()

class Discussion(Message):
    title = models.CharField(max_length=500)
    views = models.PositiveBigIntegerField(default=0)

    def save(self, *args, **kwargs):
        # Insertar manualmente en forum_message
        super().save(*args, **kwargs)
        message_id = self.id + 100
        date = datetime.now()
        cursor = connection.cursor()
        text = self.text
        if self.text == '':
            text = "''"
        message_query = "INSERT INTO forum_message (id, user_id, text, date_publication) VALUES (%s, %s, %s, %s)" % (message_id, self.user.id,text, f"'{date}'")
        print(message_query)
        cursor.executescript(message_query)
        cursor.close()
        
        cursor = connection.cursor()
        query = "INSERT INTO forum_discussion (message_ptr_id, views,title) VALUES ('%s', '%s', '%s')" % (message_id, self.views, self.title)
        print(query)
        cursor.executescript(query)  
        

class Response(Message):
    topic = models.ForeignKey(Discussion, on_delete=models.CASCADE)
    reply_to = models.ForeignKey(
        Message, on_delete=models.CASCADE, related_name='message_replied', null=True)


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'message'], name='unique_user_vote')
        ]

forum/forms.py
from typing import Text
from django import forms
from django.forms import ModelForm

from tinymce.widgets import TinyMCE

from forum.models import Discussion, Message


class MessageCreateForm(ModelForm):
    text = forms.CharField(label="Texto",
                           widget=TinyMCE(attrs={'cols': 40, 'rows': 30}),
                           required=False)

    class Meta:
        model = Message
        fields = ['text']


class DiscussionCreateForm(MessageCreateForm):
    def __init__(self, *args, **kwargs):
        super(DiscussionCreateForm, self).__init__(*args, **kwargs)
        self.fields['title'].label = "Título"

    class Meta(MessageCreateForm.Meta):
        model = Discussion
        fields = ('title', 'text')


class ContactForm(forms.Form):
    email = forms.CharField(label="Tu email")
    subject = forms.CharField(label="Asunto")
    message = forms.CharField(widget=forms.Textarea, label='Mensaje')

forum/views.py
from datetime import datetime, timedelta

import pytz
from Ageforum.settings import ROOT_URLCONF
from django.contrib.auth.password_validation import password_changed
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.db.models import Max
from django.db.models.aggregates import Min
from django.db.models.functions import Coalesce
from django.http import response
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.template.defaulttags import register
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from forum.forms import ContactForm, DiscussionCreateForm, MessageCreateForm


from .models import Discussion, Message, Response, Vote

# routes
INDEX_ROUTE = '/'

# templates urls
INDEX_TEMPLATE = 'forum/index.html'
DISCUSSION_CREATE_TEMPLATE = 'forum/discussion_create.html'
RESPONSE_CREATE_TEMPLATE = 'forum/response_create.html'
DISCUSSION_DETAIL_TEMPLATE = 'forum/discussion_detail.html'
CONTACT_TEMPLATE = 'forum/contact.html'

EDIT_DISCUSSION_TEMPLATE = 'forum/edit_text.html'
EDIT_RESPONSE_TEMPLATE = 'forum/edit_response_text.html'

RESPONSE_DELETE_TEMPLATE = 'forum/response_delete/<int:response.id>.html'
FORUM_EMAIL_ADDRESS = 'foro.age.of.empires.iv@outlook.com'

# Delete a discussion:


def delete_discussion(request, discussion_id):

    discussion = Discussion.objects.get(pk=discussion_id)
    if request.user.id != discussion.user.id:
        raise PermissionDenied()
    else:
        discussion.delete()

    return redirect(INDEX_ROUTE)


def delete_response(request, response_id):

    response = Response.objects.get(pk=response_id)

    if request.user.id != response.user.id:
        raise PermissionDenied()
    else:
        response.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def edit_text(request, discussion_id,):

    edit_text = Discussion.objects.get(pk=discussion_id)
    form = DiscussionCreateForm(data=request.POST or None, instance=edit_text)
    context = {
        'edit_text': edit_text,
        'form': form
    }
    if request.user.id != edit_text.user.id:
        raise PermissionDenied()
    else:
        if form.is_valid():
            form.save()
            return redirect('/' + str(discussion_id))
    return render(request, EDIT_DISCUSSION_TEMPLATE, context)


def edit_response_text(request, message_id,discussion_id):
    if not request.user.id:
        raise PermissionDenied()
    edit_response_text = Message.objects.get(pk=message_id)
    form = MessageCreateForm(data=request.POST or None,
                             instance=edit_response_text)
    context = {
        'edit_response_text': edit_response_text,
        'form': form
    }
    if form.is_valid():
        form.save()
        return redirect("/"+ str(discussion_id))
    return render(request, EDIT_RESPONSE_TEMPLATE, context)



def index(request):
    """
    Show all discussions ordered by last Response date
    """
    discussion_list = Discussion.objects.alias(
        latest_reply=Coalesce(
            Max('response__date_publication'), 'date_publication')
    ).order_by('-latest_reply')

    discussion_number_response_dict = __retrieve_discussion_number_response_dict(
        discussion_list)
    discussion_last_message_date_dict = __retrieve_discussion_last_message_date_dict(
        discussion_list)

    context = {
        'discussion_list': discussion_list,
        'discussion_number_response_dict': discussion_number_response_dict,
        'discussion_last_message_date_dict': discussion_last_message_date_dict
    }
    return render(request, INDEX_TEMPLATE, context)


def __retrieve_discussion_last_message_date_dict(discussion_list):
    """
    Return dictionary with date of last response for each discussion
    """
    discussion_last_message_date_dict = {}
    for discussion in discussion_list:
        last_discussion_reponse = Response.objects.filter(
            topic=discussion).order_by('date_publication').last()
        if last_discussion_reponse:
            discussion_last_message_date_dict[discussion.id] = __format_timedelta(
                datetime.now(pytz.utc) - last_discussion_reponse.date_publication)
        else:  # no responses in discussion yet -> show date of publication of discussion
            discussion_last_message_date_dict[discussion.id] = __format_timedelta(
                datetime.now(pytz.utc) - discussion.date_publication)
    return discussion_last_message_date_dict


def __format_timedelta(timedelta: timedelta):
    """
    Return timedelta in days, hours o minutes
    """
    days = timedelta.days
    hours = timedelta.seconds//3600
    minutes = timedelta.seconds//60
    if days > 0:
        return str(days) + 'd'
    elif hours > 0:
        return str(hours) + 'h'
    else:
        return str(minutes) + 'm'


def __retrieve_discussion_number_response_dict(discussion_list):
    """
    Return dictionary with number of responses for each discussion
    """
    discussion_number_response_dict = {}
    for discussion in discussion_list:
        response_count = Response.objects.filter(topic=discussion).count()
        discussion_number_response_dict[discussion.id] = response_count
    return discussion_number_response_dict


def discussion_create(request):
    """
    Show form to create a discussion when GET and create a discussion when POST. Otherwise, if user is not logged in redirects to index page
    """
    if not request.user.id:
        raise PermissionDenied()
    if request.method == 'GET':
        form = DiscussionCreateForm()
        context = {
            'form': form
        }
        return render(request, DISCUSSION_CREATE_TEMPLATE, context)
    elif request.method == 'POST':
        form = DiscussionCreateForm(data=request.POST)
        if form.is_valid():
            discussion = Discussion()
            discussion.user = request.user
            discussion.title = form.cleaned_data['title']
            discussion.text = form.cleaned_data['text']
            discussion.save()
            return HttpResponseRedirect(INDEX_ROUTE + str(discussion.id))
    else:
        raise PermissionDenied()


def response_create(request, discussion_id):
    """
    Show form to create a response when GET and create a response when POST
    """
    if not request.user.id:
        raise PermissionDenied()
    if request.method == 'GET':
        form = MessageCreateForm()
        context = {
            'form': form,
            'discussion_id': discussion_id,
        }
        return render(request, RESPONSE_CREATE_TEMPLATE, context)
    elif request.method == 'POST':
        form = MessageCreateForm(data=request.POST)
        if form.is_valid():
            response = Response()
            response.topic = get_object_or_404(Discussion, id=discussion_id)
            response.user = request.user
            response.text = form.cleaned_data['text']
            if response.text:
                response.save()
                send_mail(
                    'Foro Age of Empires IV: Han respondido en tu discusión',
                    'Han respondido en tu discusión: https://www.foroageofempiresiv.com/' +
                    str(response.topic.id),
                    FORUM_EMAIL_ADDRESS,
                    [response.topic.user.email],
                    fail_silently=False,
                )
            return HttpResponseRedirect(INDEX_ROUTE + str(discussion_id))
    else:
        raise PermissionDenied()


def discussion_detail(request, discussion_id):
    """
    Show discussion and responses
    """
    if request.method == 'GET':
        discussion = get_object_or_404(Discussion, id=discussion_id)
        response_list = Response.objects.filter(
            topic=discussion).order_by('date_publication')
        vote_count_dict = __retrieve_discussion_votes(
            discussion, response_list)
        context = {
            'discussion': discussion,
            'response_list': response_list,
            'vote_count_dict': vote_count_dict,
        }
        # if user is logged in retrieve list of votes for that user and discussion
        if request.user.id:
            messages_voted_by_user_list = __retrieve_user_discussion_votes(
                request.user, discussion)
            context['messages_voted_by_user_list'] = messages_voted_by_user_list
        return render(request, DISCUSSION_DETAIL_TEMPLATE, context)
    else:
        raise PermissionDenied()


def __retrieve_discussion_votes(discussion, response_list):
    """
    Return a dictionary of votes for given discussion and responses
    """
    vote_count_dict = {}
    vote_count_dict[discussion.id] = Vote.objects.filter(
        message=discussion).count()
    for response in response_list:
        vote_count_dict[response.id] = Vote.objects.filter(
            message=response).count()
    return vote_count_dict


def __retrieve_user_discussion_votes(user, discussion):
    """
    Return list of messages voted given user and discussion
    """
    discussion_and_responses = [discussion]
    discussion_and_responses += Response.objects.filter(topic=discussion)
    user_discussion_votes = Vote.objects.filter(
        message__in=discussion_and_responses).filter(user=user)
    messages_voted_by_user_list = []
    for vote in user_discussion_votes:
        messages_voted_by_user_list.append(vote.message)
    return messages_voted_by_user_list


@register.filter
def get_item_from_dict(dictionary, key):
    """
    Return value from key in a dictionary
    """
    return dictionary[key]


def message_vote(request, message_id):
    """
    Add or remove vote
    """
    if request.method == 'POST':
        message = get_object_or_404(Message, id=message_id)
        vote_user_message = Vote.objects.filter(
            user=request.user).filter(message=message)

templates/forum/404_error.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <title>{% block title %}Foro Age of Empires IV{% endblock %}</title>

    <link rel="stylesheet" href="{% static '/404_style.css' %}">
</head>
<body>
<div>
    <h1>ERROR 404</h1>
    <p>Volver al inicio: <a href="/">Inicio</a></p>
</div>

</body>
</html>

templates/forum/contact.html
{% extends "base.html" %}

{% block title %}Contacte con nosotros | Foro Age of Empires IV{% endblock %}

{% block content %}
<div class="container text-light">
    <div class="row mt-5">
        <div class="col-xl-6 col-md-8 col-sm-10 col-11 mx-auto">
            <form action="/contact" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-dark mb-3">Enviar</button>
            </form>
        </div>
    </div>
</div>
<script> 
    $("#id_email").addClass("form-control")
    $("#id_subject").addClass("form-control")
    $("#id_message").addClass("form-control")
</script>
{% endblock %}

templates/forum/discussion_create.html
{% extends "base.html" %}

{% block title %}Nuevo tema | Foro Age of Empires IV{% endblock %}

{% block content %}
<div class="container text-light">
    <div class="row mt-5">
        <div class="col-12 ">
            <h1 class="yellow_color">Nuevo tema de discusión</h1>
            <form action="discussion_create" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-dark">Publicar</button>
            </form>
        </div>
    </div>
</div>

<script>
    $("#id_title").addClass("form-control")
</script>
{% endblock %}

templates/forum/edit_response_text.html
{% extends "base.html" %}

{% block title %}Detalles del usuario: {{user.username}} | Foro Age of Empires IV{% endblock %}

{% block description %}
<meta name="description"
    content="Primer y único foro de Age of Empires IV en español para hispanohablantes. Detalles del usuario: {{user.username}}" />
{% endblock %}

{% block content %}
<div class="container text-light">
    <h1>Editar respuesta</h1>
    <div class="row mt-5">
        <div class="col-md-8 col-sm-10 col-12 mx-auto">
            <form action="{{discussion.id}}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-dark mb-3">Editar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/forum/edit_text.html
{% extends "base.html" %}

{% block title %}Detalles del usuario: {{user.username}} | Foro Age of Empires IV{% endblock %}

{% block description %}
<meta name="description"
    content="Primer y único foro de Age of Empires IV en español para hispanohablantes. Detalles del usuario: {{user.username}}" />
{% endblock %}

{% block content %}
<div class="container text-light">
    <h1>Editar post</h1>
    <div class="row mt-5">
        <div class="col-md-8 col-sm-10 col-12 mx-auto">
            <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-dark mb-3">Editar</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/forum/index.html
{% extends "base.html" %}

{% block description %}
<meta name="description"
    content="Primer y único foro en exclusiva de Age of Empires IV en español para hispanohablantes" />
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 col-sm-11 mx-auto">
            <h1 class="leterfont mt-5 yellow_color">BIENVENID@ A LA PRIMERA COMUNIDAD DE AGE OF EMPIRES IV PARA
                HISPANOHABLANTES</h1>
            <div class="mt-5">
                {% if request.user.id %}
                <div>
                    <a href="discussion_create" class="mb-3 mx-auto btn btn-dark">+ Nuevo tema</a>
                </div>
                {% endif %}
                <div class="mb-5" id="table_wrapper">
                    {% if discussion_list %}
                    <div class="row">
                        <div class="d-none d-xl-block">
                            <table id="discussion_table1"
                                class="table table-hover table-borderless align-middle table-striped"
                                aria-describedby="discussions table">
                                <thead class="yellow_color">
                                    <tr>
                                        <th scope="col" class="col-6 col-lg-7">Tema</th>
                                        <th scope="col" class="text-break">Respuestas</th>
                                        <th scope="col" class="text-break">Visitas</th>
                                        <th scope="col" class="text-break">Último mensaje</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for discussion in discussion_list %}
                                    <tr class="yellow_background_color">
                                        <th scope="row">
                                            <a class="black_link" href="{{discussion.id}}">
                                                {{ discussion.title }}
                                            </a>
                                        </th>
                                        <td class="text-center">
                                            {{discussion_number_response_dict|get_item_from_dict:discussion.id}}
                                        </td>
                                        <td class="text-center">{{discussion.views}}</td>
                                        <td class="text-center">
                                            {{discussion_last_message_date_dict|get_item_from_dict:discussion.id}}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="d-xl-none">
                            <table id="discussion_table2"
                                class="table table-hover table-borderless align-middle table-striped"
                                aria-describedby="discussions table">
                                <thead class="yellow_color">
                                    <tr>
                                        <th scope="col" class="col-6 col-lg-7">Tema</th>
                                        <th scope="col" class="text-break"><p class="fas fa-comment"></p></th>
                                        <th scope="col" class="text-break"><p class="fas fa-eye"></p></th>
                                        <th scope="col" class="text-break"><p class = "fas fa-clock"</p></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for discussion in discussion_list %}
                                    <tr class="yellow_background_color">
                                        <th scope="row">
                                            <a class="black_link" href="{{discussion.id}}">
                                                {{ discussion.title }}
                                            </a>
                                        </th>
                                        <td class="text-center">
                                            {{discussion_number_response_dict|get_item_from_dict:discussion.id}}
                                        </td>
                                        <td class="text-center">{{discussion.views}}</td>
                                        <td class="text-center">
                                            {{discussion_last_message_date_dict|get_item_from_dict:discussion.id}}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    {% else %}
                    <h1 class="text-danger">No hay discusiones</h1>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.11.3/datatables.min.js"></script>

<script>
    $(document).ready(function () {
        $('#discussion_table1').DataTable({
            "paging": false,
            "info": false,
            "order": [],
            columnDefs: [{
                orderable: false,
                targets: 0
            }],
            "language": {
                "search": "Buscar: "
            }
        });
        $('#discussion_table2').DataTable({
            "paging": false,
            "info": false,
            "order": [],
            columnDefs: [{
                orderable: false,
                targets: 0
            }],
            "language": {
                "search": "Buscar: "
            }
        });
        $("#discussion_table1_filter").addClass("text-light")
        $("#discussion_table2_filter").addClass("text-light")
    });
</script>
{% endblock %}

templates/forum/response_create.html
{% extends "base.html" %}

{% block title %}Responder | Foro Age of Empires
IV{% endblock %}

{% block content %}
<div class="container text-light">
    <div class="row mt-5">
        <div>
            <h1 class="yellow_color">Responder</h1>
            {% if message_to_reply %}
            <h3>Respuesta a: {{message_to_reply.text|safe|truncatechars_html:100 }}</h3>
            <form action="/response_reply_create/{{ discussion_id }}/{{message_to_reply.id}}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-dark  mb-5">Publicar</button>
            </form>
            {% else %}
            <form action="/response_create/{{ discussion_id }}" method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-dark mb-5">Publicar</button>
            </form>
            {%endif%}
        </div>
    </div>
</div>
{% endblock %}